import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillInstagram,AiFillLinkedin,AiFillGithub} from 'react-icons/ai'
import {BsFillSunFill} from 'react-icons/bs';
import Image from "next/image";
import deved from '../public/dev-ed-wave.png';
import consulting from '../public/consulting.png';
import code from '../public/code.png';
import { useState } from 'react';
export default function Home() {
  const [darkMode,setDarkMode]=useState(false);
  return (
    <div className={darkMode ? "dark": ""}>
      <Head>
        <title>Luca Ferrari Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=' bg-slate-100 px-10  dark:bg-gray-900 md:px-20 lg:px-40'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'> 
            <h1 className=' text-xl font-burton'></h1>
            <ul className='flex items-center'> 
              <li className='dark:hidden'> <BsFillMoonStarsFill onClick={() =>setDarkMode(!darkMode)}  className=' cursor-pointer text-2xl  dark:text-white'/></li>
              <li className='hidden dark:block'> <BsFillSunFill onClick={() =>setDarkMode(!darkMode) }  className=' cursor-pointer text-2xl  dark:text-white '/></li>
              <li> <a className=' bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href='#'>Contact</a></li>
            </ul>
          </nav>
          <div className=' text-center p-2'>
            <h2 className=' text-5xl py-2 text-teal-600 font-medium md:text-6xl '>Luca Ferrari</h2>
            <h3 className='text-2xl py-2  dark:text-white md:text-3xl'>Software Engeneering and Development.</h3>
            <p className=' text-md py-5 leading-8 text-gray-800  dark:text-white md:text-xl max-w-lg mx-auto'>
            Hi everyone, I'm Luca, a Computer Scientist from Genoa. I graduated in 2022 and right now i'm attending the first year of the Master's Degree in Software Security and Engineering at UniGE.</p>

          </div>
          <div className=' text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <a  className='display-hidden' href='https://github.com/luca959/luca959' target='_blank'><AiFillGithub/></a>
            <a  className='display-hidden' href='https://www.instagram.com/_.luca.ferrari._/' target='_blank'><AiFillInstagram/></a>
            <a  className='display-hidden' href='https://www.linkedin.com/in/luca-ferrari-2310a8201/' target='_blank'><AiFillLinkedin/></a>
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-5 mb-20 overflow-hidden md:w-96 md:h-96'>
            <Image src={deved} layout='fill' objectFit='cover'  />
          </div>
        </section>
        <section>

          <div className='lg:flex lg:justify-center lg:gap-20 lg:ml-10'>
          <div className=' bg-slat-50 text-center shadow-lg p-10 hover:drop-shadow-xl rounded-xl my-10 transform transition duration-500 hover:scale-125 hover:bg-slate-50  dark:bg-white lg:p-100' >
              <Image src={consulting} width={100} height={100}/>
              <h3 className=' text-lg font-medium pt-8 pb-2'>Soft Skills</h3>
              <p className=' text-gray-800 py-1'>Problem Solving</p>
              <p className=' text-gray-800 py-1'>Team Bulding</p>
              <p className=' text-gray-800 py-1'>Team Working</p>
              <p className=' text-gray-800 py-1'>Creativity</p>
              <p className=' text-gray-800 py-1'>Computational Thinking</p>


            </div>
            <div className=' bg-slat-50 text-center shadow-lg p-10 hover:drop-shadow-xl rounded-xl my-10 transform transition duration-500 hover:scale-125 hover:bg-slate-50  dark:bg-white lg:p-100' >
              <Image src={code} width={100} height={100}/>
              <h3 className=' text-lg font-medium pt-8 pb-2 '>Programming Languages </h3>
              <p className=' text-gray-800 py-1'><span className='font-bold'>C++ </span>- Proficient</p>
              <p className=' text-gray-800 py-1'><span className='font-bold'> C </span>- Intermediate</p>
              <p className=' text-gray-800 py-1'><span className='font-bold'>Java</span> - Intermediate</p>
              <p className=' text-gray-800 py-1'><span className='font-bold'>Python </span>- Intermediate</p>
              <p className=' text-gray-800 py-1'><span className='font-bold'>HTML</span> - Intermediate</p>
              <p className=' text-gray-800 py-1'><span className='font-bold'>PHP </span>- Intermediate</p>
              <p className=' text-gray-800 py-1' ><span className='font-bold'>CSS </span>- Intermediate</p>   
              <p className=' text-gray-800 py-1'><span className='font-bold'>Javascript </span>- Intermediate</p>
              <p className=' text-gray-800 py-1'><span className='font-bold'>Flask</span> - Intermediate</p>
              <p className=' text-gray-800 py-1'><span className='font-bold'>Next.js</span> - Intermediate</p>
              <p className=' text-gray-800 py-1'><span className='font-bold'>Svelte </span>- Intermediate</p>
            </div>
          </div>

        </section>
        <section>
          <div>
            <br></br>
            <br></br>
          </div>
        </section>
    
      </main>

    
    </div>
  );
}
